2017-12-12 04:26:09:	Starting Log...
2017-12-12 04:26:09:	logInfo	ID:475538055	First:QlikBotNet	Last:	UserName:qlikbotnetbot	<Timer for alerts started with 60 seconds>
2017-12-12 04:26:09:	Starting Log...
2017-12-12 04:26:09:	Started and Callback set for Bot 
2017-12-12 04:26:12:	logError	ID:475538055	First:QlikBotNet	Last:	UserName:qlikbotnetbot	<Error opening the Qlik Sense app : Qlik.Sense.JsonRpc.CommunicationErrorException: Connection failed after 4 attempts. Error message:
  Could not load file or assembly 'Autofac, Version=4.6.2.0, Culture=neutral, PublicKeyToken=17863af14b0044da' or one of its dependencies. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Autofac, Version=4.6.2.0, Culture=neutral, PublicKeyToken=17863af14b0044da' or one of its dependencies. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Autofac, Version=3.5.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da' or one of its dependencies. The system cannot find the file specified.
   --- End of inner exception stack trace ---
   at Qlik.Sense.JsonRpc.WebSocketFactory.<>c.<GetWebSocketFactory>b__3_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Qlik.Sense.JsonRpc.Location.GetDefaultSecurityConfiguration()
   at Qlik.Sense.JsonRpc.Location.get_Security()
   at Qlik.Sense.JsonRpc.Location.GetWebSocketSessionContainer(ISession session)
   at Qlik.Sense.JsonRpc.RpcConnection.<OpenAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Qlik.Sense.JsonRpc.RpcConnection.<EnsureConnectionIsOpen>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Qlik.Sense.JsonRpc.RpcConnection.<SendAsync>d__52.MoveNext()
   --- End of inner exception stack trace ---
   at Qlik.Engine.Communication.QlikConnection.AwaitResponseTask[T](T task, String methodName, CancellationToken cancellationToken)
   at Qlik.Engine.Communication.QlikConnection.Ping(Nullable`1 noVersionCheck)
   at Qlik.Engine.LocationExtensions.Hub(ILocation location, ISession session, Nullable`1 noVersionCheck)
   at Qlik.Engine.LocationExtensions.GetAppIdentifiers(ILocation location, Nullable`1 noVersionCheck)
   at Qlik.Engine.LocationExtensions.AppWithIdOrDefault(ILocation location, String appId, Nullable`1 noVersionCheck)
   at QlikSenseEasy.QSApp.QSOpenApp() in C:\Users\baz\Documents\GitHub\QlikBotNet\Bot Development\QlikSenseEasy\QSEasy.cs:line 357
   at QlikTelegram.Bot..ctor() in C:\Users\baz\Documents\GitHub\QlikBotNet\Bot Development\QlikTelegram\Bot.cs:line 163>
2017-12-12 04:26:12:	logInfo	ID:475538055	First:QlikBotNet	Last:	UserName:qlikbotnetbot	<Created a conversation with Google Api.Ai.>
2017-12-12 04:26:14:	logError	BotOnReceiveError: Telegram.Bot.Args.ReceiveErrorEventArgs
2017-12-12 04:26:17:	logInfo	Message Received from 481378768: dimensions
2017-12-12 04:26:17:	logInfo	ID:481378768	First:wuzhong	Last:zhu	UserName:	<Could not connect to the Qlik Sense server: https://qlikbot.qlik.com for user 481378768 (wuzhong zhu)>
2017-12-12 04:26:23:	logError	BotOnReceiveError: Telegram.Bot.Args.ReceiveErrorEventArgs
2017-12-12 04:26:28:	logError	BotOnReceiveError: Telegram.Bot.Args.ReceiveErrorEventArgs
2017-12-12 04:26:33:	logError	BotOnReceiveError: Telegram.Bot.Args.ReceiveErrorEventArgs
2017-12-12 04:26:38:	logError	BotOnReceiveError: Telegram.Bot.Args.ReceiveErrorEventArgs
