2017-12-11 07:13:08:	Starting Log...
2017-12-11 07:13:08:	logInfo	ID:485420868	First:Qlik Cool Bot	Last:	UserName:WZQlikCoolBot	<Timer for alerts started with 60 seconds>
2017-12-11 07:13:08:	Starting Log...
2017-12-11 07:13:08:	Started and Callback set for Bot 
2017-12-11 07:13:10:	logError	ID:485420868	First:Qlik Cool Bot	Last:	UserName:WZQlikCoolBot	<Error opening the Qlik Sense app : Qlik.Sense.JsonRpc.CommunicationErrorException: Connection failed after 4 attempts. Error message:
  Could not load file or assembly 'Autofac, Version=4.6.2.0, Culture=neutral, PublicKeyToken=17863af14b0044da' or one of its dependencies. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Autofac, Version=4.6.2.0, Culture=neutral, PublicKeyToken=17863af14b0044da' or one of its dependencies. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Autofac, Version=3.5.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da' or one of its dependencies. The system cannot find the file specified.
   --- End of inner exception stack trace ---
   at Qlik.Sense.JsonRpc.WebSocketFactory.<>c.<GetWebSocketFactory>b__3_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Qlik.Sense.JsonRpc.Location.GetDefaultSecurityConfiguration()
   at Qlik.Sense.JsonRpc.Location.get_Security()
   at Qlik.Sense.JsonRpc.Location.GetWebSocketSessionContainer(ISession session)
   at Qlik.Sense.JsonRpc.RpcConnection.<OpenAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Qlik.Sense.JsonRpc.RpcConnection.<EnsureConnectionIsOpen>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Qlik.Sense.JsonRpc.RpcConnection.<SendAsync>d__52.MoveNext()
   --- End of inner exception stack trace ---
   at Qlik.Engine.Communication.QlikConnection.AwaitResponseTask[T](T task, String methodName, CancellationToken cancellationToken)
   at Qlik.Engine.Communication.QlikConnection.Ping(Nullable`1 noVersionCheck)
   at Qlik.Engine.LocationExtensions.Hub(ILocation location, ISession session, Nullable`1 noVersionCheck)
   at Qlik.Engine.LocationExtensions.GetAppIdentifiers(ILocation location, Nullable`1 noVersionCheck)
   at Qlik.Engine.LocationExtensions.AppWithIdOrDefault(ILocation location, String appId, Nullable`1 noVersionCheck)
   at QlikSenseEasy.QSApp.QSOpenApp() in C:\Users\baz\Documents\GitHub\QlikBotNet\Bot Development\QlikSenseEasy\QSEasy.cs:line 357
   at QlikTelegram.Bot..ctor() in C:\Users\baz\Documents\GitHub\QlikBotNet\Bot Development\QlikTelegram\Bot.cs:line 163>
2017-12-11 07:13:10:	logInfo	ID:485420868	First:Qlik Cool Bot	Last:	UserName:WZQlikCoolBot	<Created a conversation with Google Api.Ai.>
2017-12-11 07:13:14:	logError	BotOnReceiveError: Telegram.Bot.Args.ReceiveErrorEventArgs
2017-12-11 07:13:14:	logInfo	Message Received from 481378768: report
2017-12-11 07:13:14:	logInfo	ID:481378768	First:wuzhong	Last:zhu	UserName:	<Could not connect to the Qlik Sense server: https://sense-demo.qlik.com/site for user 481378768 (wuzhong zhu)>
2017-12-11 07:13:15:	logInfo	Sent text message <Choose a report> to ChatID 481378768
2017-12-11 07:13:22:	logError	BotOnReceiveError: Telegram.Bot.Args.ReceiveErrorEventArgs
2017-12-11 07:13:22:	logError	Failed send doc message. Telegram.Bot.Exceptions.ApiRequestException: Request timed out ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__109`1.MoveNext()
   --- End of inner exception stack trace ---
   at Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__109`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at QlikTelegram.Bot.<BotSendDocMessage>d__53.MoveNext() in C:\Users\baz\Documents\GitHub\QlikBotNet\Bot Development\QlikTelegram\Bot.cs:line 1149 Exception caught.
2017-12-11 07:13:27:	logError	BotOnReceiveError: Telegram.Bot.Args.ReceiveErrorEventArgs
2017-12-11 07:13:32:	logError	BotOnReceiveError: Telegram.Bot.Args.ReceiveErrorEventArgs
